#+SETUPFILE: ~/.emacs.d/org-templates/level-1.org
#+TITLE: 2017 观影
#+FILETAGS: :movie:2017
#+LATEX_CLASS: cn-article
#+AUTHOR: Billyhuang@sina.cn
* 一月
** 星球大战外传：侠盗一号 Rogue One: A Star Wars Story
 + 导演: 加里斯·爱德华斯
 + 主演: 菲丽希缇·琼斯 / 迭戈·鲁纳 / 甄子丹 / 本·门德尔森 / 麦斯·米科尔森
 + 类型: 动作 / 科幻 / 冒险
保持好莱坞一贯的大片品质。少了些美式个人英雄主义，更多的描述集体与合作。也看到了些许中国资本的力量。任何和平都来之不易，愿世界少些纷争，多些关爱。

** 情圣
 + 导演: 宋晓飞 / 董旭
 + 主演: 肖央 / 闫妮 / 小沈阳 / 乔杉 / 艾伦
 + 类型: 喜剧
步入中年生活缺少了激情与新鲜感，此时遇到了一个能给你带来久违的怦然心动的人，你会做出何种荒唐的事情，说下多少弥天大谎？面对内心欲望与家庭责任你会如何择选？\\
其实对电影本身内容的感触到不是很深切，毕竟这种中年困惑离我还有一段距离。倒是在观影时，想到了中国电影分级的事情。拿这部片子来说，当中充斥着大量的性暗示和少年不宜的段子。
个人觉得至少应该是一部定位在16+的影片。在未有任何官方指导的情况下，总是会有些选片不认真的家长，或者说过度相信广电总局的家长。带着几岁或是十几岁的小孩观看此类片子。实在是不合适。
当就目前来看大陆电影市场要实现分级制度，还不知道要等到猴年马月…… 还是各位家长们多长长心吧，带着小朋友看片时，选片慎重些吧。

* 二月
** 乘风破浪
 + 导演: 韩寒
 + 主演: 邓超 / 彭于晏 / 赵丽颖 / 董子健 / 金士杰
 + 类型: 剧情 / 喜剧
如果不要太在意细节，太在意逻辑。其实做为一个娓娓道来的故事看，还算是一部不错的片子吧。在国产电影被各种小鲜肉，卖卖帅，耍耍酷就能换取高票房的情况下，这还算是一部制作水平用心程度上乘的国产作品吧。\\
愿国内影视圈少些鲜肉，多些干货。当然即是鲜肉又有干肉，那当然是非常欢迎的。

** 功夫瑜伽
 + 导演: 唐季礼
 + 主演: 成龙 / 李治廷 / 张艺兴 / 索努·苏德 / 母其弥雅
 + 类型: 喜剧 / 动作 / 冒险
对这部片子真的没啥可说的，看个乐呵吧。打打闹闹，说说笑笑过新年。不过友情提示：豺狼和狮子可不会像电影中表现的那么温柔。珍爱生命，远离它们。

** 爱乐之城 La La Land
 + 导演: 达米安·沙泽勒
 + 主演: 瑞恩·高斯林 / 艾玛·斯通 / 约翰·传奇 / J·K·西蒙斯 / 罗丝玛丽·德薇特
 + 类型: 剧情 / 爱情 / 歌舞
看完这部电影，感慨颇多。关于传统文化传承、关于梦想的追求、关于爱。\\
 + 文化传承
片中提到的传统爵士的没落，亦如京剧、越剧、黄梅戏等传统中国戏曲的没落。如何去传承这些文化，如何让更多人热爱这些传统文化，特别是儿童、年轻人。都是一个非常值得探讨的问题。是自我革新顺应时代的发展？还是保持传统魅力但缺变得小众？或是又有什么办法能够两者兼得？这需要更专业人士去思考，更多人，更多资源去关注。愿未来的世界多姿多彩。
 + 梦想追求
对梦想坚持不懈的追求，让我们的生活充满活力，让我们的生命更有意义。但是又有多少人能够坚持到最后，能够不被现实的生活给打败。或许正是梦想的遥不可及，才让它有如此的魅力。不是有句话说：容易实现的就不是梦想吗！希望更多的人勇于追逐自己的梦想，不要被生活拖垮，不要被世俗的眼光和言语击败。致敬那些赏有梦想的人，致敬那些踏上梦想之路的人。
 + 爱
爱，永恒的话题。这或许是上帝最得意的创造吧。在人生的道路上，我们都希望能找到一个彼此欣赏、彼此鼓励，能够相濡以沫、也能够共享人生荣华富贵的人吧。但是现实缺并不那么完美，总会在错的时间，错的地点，却遇上了对的人。最后因为总总原因，遗憾的错过，犹如影片中男女主人公。但是这又何尝不是另一种完美，
在茫茫世界中，有一个本和你毫无关系的人。默默的牵挂着你，祝福着你，而你亦如此。
