#+SETUPFILE: ~/.emacs.d/org-templates/level-1.org
#+TITLE: 2017 观影
#+FILETAGS: :movie:2017
#+LATEX_CLASS: cn-article
#+AUTHOR: Billyhuang@sina.cn
* 一月
** 星球大战外传：侠盗一号 Rogue One: A Star Wars Story
 + 导演: 加里斯·爱德华斯
 + 主演: 菲丽希缇·琼斯 / 迭戈·鲁纳 / 甄子丹 / 本·门德尔森 / 麦斯·米科尔森
 + 类型: 动作 / 科幻 / 冒险
保持好莱坞一贯的大片品质。少了些美式个人英雄主义，更多的描述集体与合作。也看到了些许中国资本的力量。任何和平都来之不易，愿世界少些纷争，多些关爱。

** 情圣
 + 导演: 宋晓飞 / 董旭
 + 主演: 肖央 / 闫妮 / 小沈阳 / 乔杉 / 艾伦
 + 类型: 喜剧
步入中年生活缺少了激情与新鲜感，此时遇到了一个能给你带来久违的怦然心动的人，你会做出何种荒唐的事情，说下多少弥天大谎？面对内心欲望与家庭责任你会如何择选？\\
其实对电影本身内容的感触到不是很深切，毕竟这种中年困惑离我还有一段距离。倒是在观影时，想到了中国电影分级的事情。拿这部片子来说，当中充斥着大量的性暗示和少年不宜的段子。
个人觉得至少应该是一部定位在16+的影片。在未有任何官方指导的情况下，总是会有些选片不认真的家长，或者说过度相信广电总局的家长。带着几岁或是十几岁的小孩观看此类片子。实在是不合适。
当就目前来看大陆电影市场要实现分级制度，还不知道要等到猴年马月…… 还是各位家长们多长长心吧，带着小朋友看片时，选片慎重些吧。

* 二月
** 乘风破浪
 + 导演: 韩寒
 + 主演: 邓超 / 彭于晏 / 赵丽颖 / 董子健 / 金士杰
 + 类型: 剧情 / 喜剧
如果不要太在意细节，太在意逻辑。其实做为一个娓娓道来的故事看，还算是一部不错的片子吧。在国产电影被各种小鲜肉，卖卖帅，耍耍酷就能换取高票房的情况下，这还算是一部制作水平用心程度上乘的国产作品吧。\\
愿国内影视圈少些鲜肉，多些干货。当然即是鲜肉又有干肉，那当然是非常欢迎的。

** 功夫瑜伽
 + 导演: 唐季礼
 + 主演: 成龙 / 李治廷 / 张艺兴 / 索努·苏德 / 母其弥雅
 + 类型: 喜剧 / 动作 / 冒险
对这部片子真的没啥可说的，看个乐呵吧。打打闹闹，说说笑笑过新年。不过友情提示：豺狼和狮子可不会像电影中表现的那么温柔。珍爱生命，远离它们。
